name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Tests & Format Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 24.x
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npx prettier --check "{src,test}/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Build Nearley grammars
        run: npm run build:grammar

      - name: Run Jest tests
        run: npx jest
